### ISSUE TITLE
B2 support

### ISSUE THREAD

**Issue by rhnvrm** [rhnvrm/simples3#17]
Discussion forked from https://github.com/knadh/listmonk/issues/617

**Comment by devinellis** [comment]
FWIW, I checked the CMS I use (Directus) and they use the nodejs `aws-sdk` package and call this `upload` method, which looks like a wrapper around PutObject: https://github.com/aws/aws-sdk-js/blob/master/lib/services/s3.d.ts#L39. Uploads work fine to B2 using this CMS.

**Comment by rhnvrm** [comment]
Hey

On further preliminary investigation, it seems B2 does not support POST calls properly. I've added support for s3 PUT calls in #18 which should ideally be supported on B2.

**Comment by kamikazechaser** [comment]
Tested this on B2, returns a 400. Not sure if B2 rejects AWS style signed requests. Does this library intend to support alternative s3 compatible implementations i.e. MinIO,  BackBlaze, e.t.c. ? Because some s3 clones don't support regions, have different path styles, e.t.c.

**Comment by rhnvrm** [comment]
Hi

This library is tested against MinIO (in github pipelines) and AWS s3 (locally) so it should work with most compatible alternatives to s3. I have personally used Wasabi as well which works fine. 

B2 seems to _not_ support POST upload calls. I have added s3 PUT upload calls in #18 which can be used as an alternative for uploading files on B2 (and should work fine with other providers as well).

**Comment by kamikazechaser** [comment]
Yeah, I did specifically test B2 with the FilePut call but got a 400. I'll dump the HTTP trace and get back to you.

**Comment by calebfaruki** [comment]
I'm also getting a 400 error.

```
2022/03/23 21:23:08error uploading file: status code: 400 : "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n <Code>InvalidRequest</Code>\n <Message>Timestamp '20220323T212308Z' is invalid</Message>\n</Error>\n"
```
