### ISSUE TITLE
Temporary session tokens don't seem to work

### ISSUE THREAD

**Issue by mr-karan** [rhnvrm/simples3#24]
I've the following tokens in my env:

```
AWS_ACCESS_KEY_ID=REDACTED
AWS_SECRET_ACCESS_KEY=REDACTED
AWS_SESSION_TOKEN=REDACTED
```

With this simple initializing code:

```
	var (
		accessKey, _ = os.LookupEnv("AWS_ACCESS_KEY_ID")
		secretKey, _ = os.LookupEnv("AWS_SECRET_ACCESS_KEY")
		region, _    = os.LookupEnv("AWS_DEFAULT_REGION")
		token, _     = os.LookupEnv("AWS_SESSION_TOKEN")
	)

	// Set a default region.
	if region == "" {
		region = "ap-south-1"
	}

	// Lookup for env keys if they are present and initalise S3 based on those keys.
	if accessKey != "" && secretKey != "" {
		s3 := simples3.New(region, accessKey, secretKey)
		s3.SetToken(token)
		return s3
	} else {
		// Else check if IAM is accessible in this env.
		s3, err := simples3.NewUsingIAM(region)
		if err != nil {
			fmt.Println("error initialising s3 client using IAM: %v", err)
			os.Exit(1)
		}
		return s3
	}
```

I am trying to access a bucket and these credentials have access to them. With `simpleS3` I am getting `status code: 403 Forbidden` on .FileDownload() method.

However, same works when I do:

```
aws s3 cp s3://my-bucket/my-key/data.json /tmp/data.json
download: s3://my-bucket/my-key/data.json to ../../../../../../tmp/data.json
```

I tried creating a temporary user with just access key/secret key and with same IAM policies attached and I was able to access it via simpleS3... which makes me wonder if this `.Token` is not being used properly.

**Comment by rhnvrm** [comment]
Hi

The support for security tokens was added in #4 

It seems it was only added to support presigned URLs.

I have added a check to add the header in the branch `fix-security-token`.

Since its a bit difficult to test this, would it be possible to test if the patch works at your end?

https://github.com/rhnvrm/simples3/tree/fix-security-token

**Comment by mr-karan** [comment]
@rhnvrm That fixes it. Thanks :+1:

**Comment by rhnvrm** [comment]
https://github.com/rhnvrm/simples3/releases/tag/v0.8.3

You can now use this version. Thanks
