### ISSUE TITLE
Encoding issues for object keys with special characters

### ISSUE THREAD

**Issue by jacksgt** [rhnvrm/simples3#7]
Hey,

so I stumbled across something odd. Uploading files with filenames containing special characters works flawlessly, but downloading or deleting them fails. In my particular case, my local [Minio instance](https://docs.minio.io/) complains that the request signature does not match, but I think that is just a side effect.

Consider this test example:
```go
package storage

import (
	"bytes"
	"path"
	"testing"

	"github.com/rhnvrm/simples3"
)

func TestFileName(t *testing.T) {
	inData := []byte("HelloWorld\nFooBar\nOneTwoThree\n")
	testKey := "example?file%with$special&chars(1).txt"

	s3 = simples3.New("S3Region", "S3AccessKey", "S3SecretKey")
	s3.SetEndpoint("http://localhost:9000")

	_, err := s3.FileUpload(simples3.UploadInput{
		Bucket:      "simples3",
		ObjectKey:   testKey,
		ContentType: "text/plain",
		FileName:    path.Base(testKey),
		Body:        bytes.NewReader(inData),
	})
	if err != nil {
		t.Fatalf("Failed to store file %s: %s", testKey, err)
		return
	}
	_, err = s3.FileDownload(simples3.DownloadInput{
		Bucket:    "simples3",
		ObjectKey: testKey,
	})
	if err != nil {
		t.Fatalf("Failed to get file %s: %s", testKey, err)
	}

	err = s3.FileDelete(simples3.DeleteInput{
		Bucket:    "simples3",
		ObjectKey: testKey,
	})
	if err != nil {
		t.Fatalf("Failed to delete file %s: %s\n", testKey, err)
	}
}
```

It fails with the following error (`go test -run.test TestFileName simples3_test.go`):
```
--- FAIL: TestFileName (0.11s)
    simples3_test.go:35: Failed to get file example?file%with$special&chars(1).txt: status code: 403 Forbidden
```

The Server logs the following:
```
localhost [REQUEST s3.PostPolicyBucket] 12:11:08.211
localhost POST /simples3
localhost Host: localhost:9000
localhost Accept-Encoding: gzip
localhost Content-Length: 1938
localhost Content-Type: multipart/form-data; boundary=8f92e8553bf46e645c1f13ef35cb60bc203127facf66cdbcf215f5b2f690
localhost User-Agent: Go-http-client/1.1
localhost <BODY>
localhost [RESPONSE] [12:11:08.211] [ Duration 8.449ms  ↑ 2.0 KiB  ↓ 691 B ]
localhost 201 Created
localhost X-Amz-Request-Id: 16409DE3997F5B48
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost ETag: "ea3b2e64587b58a724e2f5a15a45a1f7-1"
localhost Content-Type: application/xml
localhost Location: http://localhost:9000/simples3/example%3Ffile%25with$special&chars%281%29.txt
localhost Server: MinIO/RELEASE.2020-02-20T22-51-23Z
localhost Vary: Origin
localhost Content-Length: 305
localhost Content-Security-Policy: block-all-mixed-content
localhost <BODY>
localhost 
localhost [REQUEST s3.GetObject] 12:11:08.212
localhost GET /simples3/example?file%with$special&chars(1).txt
localhost Host: localhost:9000
localhost Authorization: REDACTED
localhost Content-Length: 0
localhost Date: 20201023T121108Z
localhost User-Agent: Go-http-client/1.1
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost Accept-Encoding: gzip
localhost <BODY>
localhost [RESPONSE] [12:11:08.212] [ Duration 467µs  ↑ 87 B  ↓ 658 B ]
localhost 403 Forbidden
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost Content-Length: 401
localhost Content-Security-Policy: block-all-mixed-content
localhost Content-Type: application/xml
localhost Server: MinIO/RELEASE.2020-02-20T22-51-23Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 16409DE39A0FE29B
localhost <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>example</Key><BucketName>simples3</BucketName><Resource>/simples3/example</Resource><RequestId>16409DE39A0FE29B</RequestId><HostId>4a57eb7d-dd77-496f-aee1-f604ca81f4f8</HostId></Error>
localhost 
```

On the server side, the file is correctly stored as `example?file%with$special&chars(1).txt`.

--------

So, my suspicion here is that URL-encoding is not necessary when POSTing the object (because the object key is in the body), but it is necessary for GET and DELETE requests, because the object key is part of the URL.

What do you think about this? Should the Upload and Delete functions maybe by default URL-encode the object key?

**Comment by jacksgt** [comment]
By the way, I managed to work around this issue by prepending the calls to UploadFile and DeleteFile with the following snippet:
```go
	key := "hello!/world/foo(1).pdf"
	paths := strings.Split(key, "/")
	for k, _ := range paths {
		paths[k] = url.PathEscape(paths[k])
	}
	key = strings.Join(paths, "/")
```
It is not possible to just use `url.PathEscape` or `url.QueryEscape` on the entire object key, because slashes `/` need to be preserved (but maybe there is a more efficient way of doing this).

**Comment by rhnvrm** [comment]
@jacksgt 

I'm not sure if changing the key while uploading would be correct. I guess we just need to encode it while doing GET/DELETE etc. 

I found this package written in javascript which might be useful, https://github.com/GeorgePhillips/node-s3-url-encode/blob/master/index.js

Would it be possible for you to test if this works? If not, ill try to test it myself in a few days.

**Comment by jacksgt** [comment]
Hey, thanks for getting back!
You are correct, I meant to refer to `GetFile` instead of `UploadFile` in my previous comment (corrected).
I will port the function you suggested to Go and try it out in the coming days.

**Comment by jacksgt** [comment]
I can indeed confirm that the following match-replacement function (applied before `GetFile` and `DeleteFile`) works:
```go
var encodings = map[string]string{
	`+`: `%2B`,
	`!`: `%21`,
	`"`: `%22`,
	`#`: `%23`,
	`$`: `%24`,
	`&`: `%26`,
	"`": `%27`,
	`(`: `%28`,
	`)`: `%29`,
	`*`: `%2A`,
	`,`: `%2C`,
	`:`: `%3A`,
	`;`: `%3B`,
	`=`: `%3D`,
	`?`: `%3F`,
	`@`: `%40`,
}

func encodeS3Uri(key string) string {
	return regexp.MustCompile(
		`(\+|!|"|#|\$|&|'|\(|\)|\*|\+|,|:|;|=|\?|@)`,
	).ReplaceAllStringFunc(
		url.PathEscape(key),
		func(match string) string {
			return encodings[match]
		},
	)
}
```
But I think we need to take a closer look at what `url.PathEscape` is already doing (and what it's not doing), especially since this encoding must not be applied to slashes (`/`) in the object key (AFAIK).

**Comment by jacksgt** [comment]
The original PathEscape and PathUnescape function for Go were discussed [here](https://github.com/golang/go/issues/13737) and added [here](https://go-review.googlesource.com/c/go/+/31322/3/src/net/url/url.go). For some reason, they didn't go for their initial design which would have "skipped over" slashes, i.e. leaving them in place (because now PathEscape is running in `encodePathSegment` mode instead of `encodePath` mode: https://golang.org/src/net/url/url.go#L280)

However, this functionality can still be used via (URL).EscapedPath() https://golang.org/src/net/url/url.go#L700

**Comment by rhnvrm** [comment]
Hmm... Interesting.

Although, revisiting the encoder code we ported here, can't we just skip the `url.PathEscape` inside it. 

Can you please confirm if this is the correct key produced by the function and works on your minio instance?

```
package main

import (
	"fmt"
	"regexp"
)

var encodings = map[string]string{
	`+`: `%2B`,
	`!`: `%21`,
	`"`: `%22`,
	`#`: `%23`,
	`$`: `%24`,
	`&`: `%26`,
	"`": `%27`,
	`(`: `%28`,
	`)`: `%29`,
	`*`: `%2A`,
	`,`: `%2C`,
	`:`: `%3A`,
	`;`: `%3B`,
	`=`: `%3D`,
	`?`: `%3F`,
	`@`: `%40`,
}

func encodeS3Uri(key string) string {
	return regexp.MustCompile(
		`(\+|!|"|#|\$|&|'|\(|\)|\*|\+|,|:|;|=|\?|@)`,
	).ReplaceAllStringFunc(
		key,
		func(match string) string {
			return encodings[match]
		},
	)
}

func main() {
	key := "hello!/world/foo(1).pdf"
	fmt.Println(encodeS3Uri(key))
	
	// Output: hello%21/world/foo%281%29.pdf
}
```

**Comment by jacksgt** [comment]
Hey, I tried your function and it works, though I had to extend the encoding with the space (` `) character.
However, in general I am not confident we can just skip PathEscape, because in general there are many other characters that might need to be encoded:
https://www.w3schools.com/tags/ref_urlencode.asp

**Comment by rhnvrm** [comment]
Hey @jacksgt, would you want to still port this function and send a PR? Else, I'd be happy to take a look at this.

**Comment by jacksgt** [comment]
Sure, if you are fine with that approach, I will try to look into it over the next few days :-)
